Tugas1PPW/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.views.generic.base import RedirectView
import add_friend.urls as add_friend
import update_status.urls as update_status
import dashboard.urls as dashboard
import page_profile.urls as page_profile

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^update-status/', include(update_status,namespace='update-status')),
	url(r'^add-friend/', include(add_friend,namespace='add-friend')),
	url(r'^dashboard/', include(dashboard,namespace='dashboard')),
	url(r'^page_profile/', include(page_profile,namespace='page_profile')),
	url(r'^$', RedirectView.as_view(url="update-status/", permanent="true"), name='index'),
]

add_friend/urls.py
from django.conf.urls import url
from .views import index, add_friend_post


urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^add_friend', add_friend_post, name='add_friend'),
	]

dashboard/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
	url(r'^$', index, name='index'),
]

page_profile/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

update_status/urls.py
from django.conf.urls import url
from .views import index, add_post, add_comment, save_comment

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^add-post', add_post, name='add-post'),
	url(r'^add-comment/(?P<pk>[0-9]+)/$', add_comment, name='add-comment'),
	url(r'^save-comment/(?P<pk>[0-9]+)/$', save_comment, name='save-comment'),
	url(r'^cancel', index, name='cancel'),
]

add_friend/models.py
from django.db import models

# Create your models here.

class Friend_List(models.Model):
	name = models.CharField(max_length=27)
	url = models.URLField(max_length=200)
	created_date = models.DateTimeField(auto_now_add=True)

dashboard/models.py
from django.db import models

# Create your models here.

page_profile/models.py
from django.db import models

update_status/models.py
from django.db import models

class Post(models.Model):
	post = models.CharField(max_length=1600)
	created_date = models.DateTimeField(auto_now_add=True)
	
class Comment(models.Model):
	comment = models.CharField(max_length=1600)
	created_date = models.DateTimeField(auto_now_add=True)
	post = models.ForeignKey(Post, null=True, blank=True)

add_friend/forms.py
from django import forms

class Add_Friend_Form(forms.Form):
    error_messages = {
        'required': 'Isi terlebih dahulu',

    }
    attrs_name = {
        'placeholder': 'masukkan nama',
    }
    attrs_url = {
        'placeholder': 'masukkan url',
    }

    name = forms.CharField(label='Nama', required=True, max_length=27, widget=forms.TextInput(attrs=attrs_name))
    url = forms.URLField(required=True, widget=forms.URLInput(attrs=attrs_url))

update_status/forms.py
from django import forms

class Post_Form(forms.Form):
	error_messages = {
		'required': 'Post Tidak Boleh Kosong',
	}
	attrs = {
		'class': 'text-design',
		'placeholder':"Apa yang anda pikirkan ....",
	}
	post = forms.CharField(error_messages=error_messages, label="", required=True, max_length=1600, widget=forms.Textarea(attrs=attrs))

add_friend/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Add_Friend_Form
from .models import Friend_List



response = {} 
def index(request):
	html = 'add_friend.html'
	response['add_friend_form'] = Add_Friend_Form

	friend = Friend_List.objects.all()
	response['friend'] = friend
	return render(request, html, response)

def add_friend_post(request):
	form = Add_Friend_Form(request.POST or None)
	if(request.method == 'POST' and form.is_valid()):
		print('valid')
		response['name'] = request.POST['name']
		response['url'] = request.POST['url']
		friend = Friend_List(name=response['name'], url=response['url'])
		friend.save()

		html ='add_friend.html'

		return HttpResponseRedirect('/add-friend/')
	else:        
		return HttpResponseRedirect('/add-friend/')

dashboard/views.py
from django.shortcuts import render
from update_status.models import Post
from add_friend.models import Friend_List

def index(request):
	author = 'Hepzibah Smith'
	posts = Post.objects.all().count()
	
	if posts == 0:
		temp = Post(post = 'Hi')
		temp.save()
	
	latest_post = Post.objects.last().post
		
	date = Post.objects.last().created_date
	friend = Friend_List.objects.all().count()
	
	response = {'author':author, 'posts':posts, 'date':date, 'latest_post':latest_post, 'friend':friend}
	return render(request, 'statistic.html', response)
	

page_profile/views.py
from django.shortcuts import render
from datetime import datetime, date

response = {'name': 'Hepzibah Smith', 'bday': '01 jan', 'gender': 'Female', 'expertise': ['coding', 'webDev', 'eat'], 'desc': 'antique expert. expert in web programming and design', 'email': 'hello@smith.com'}
def index (request):
	return render (request, 'page_profile/tampilan.html', response)
	

update_status/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Post_Form
from .models import Post, Comment
from page_profile.views import response as res
# Create your views here.

response = {}
def index(request):
	html = 'update_status/updateStatus.html'
	response['post_form'] = Post_Form
	post = Post.objects.order_by('-created_date')
	com = Comment.objects.order_by('-created_date')
	response['post'] = post
	response['comments'] = com
	response['nama'] = res['name']
	return render(request, html, response)

def add_post(request):
	form = Post_Form(request.POST or None)
	if(request.method == 'POST' and form.is_valid()):
		response['post'] = request.POST['post']
		post = Post(post=response['post'])
		post.save()
	return HttpResponseRedirect('/update-status/')

def add_comment(request, pk):
	html = 'update_status/addComment.html'
	response['post_forms'] = Post_Form
	response['posted'] = Post.objects.get(pk=pk)
	return render(request, html, response)

def save_comment(request, pk):
	post = Post.objects.get(pk=pk)
	form = Post_Form(request.POST or None)
	if(request.method == 'POST' and form.is_valid()):
		response['comments'] = request.POST['post']
		com = Comment(comment=response['comments'])
		com.post = post
		com.save()
	return HttpResponseRedirect('/update-status/')

add_friend/templates/add_friend.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/add_friend.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet">
    <!-- <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet"> -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>add_friend</title>
</head>

<body>

    <header>
        {% include "partials/header.html" %}
        <script>
            function myFunction() {
                var x = document.getElementById("myTopnav");
                if (x.className === "topnav") {
                    x.className += " responsive";
                } else {
                    x.className = "topnav";
                }
            }
        </script>
    </header>

    <h2 id='add-friend' class='OpenSansFont center'>Add Friend</h2>
    <div class='box'>
        <form class='center' method="POST" action="{% url 'add-friend:add_friend' %}">
            {% csrf_token %}
            <div>Name</div>
            <div id="form-name">{{ add_friend_form.name }}</div>
            <div>URL</div>
            <div id="form-url">{{ add_friend_form.url }}</div>
            <br>
            <div class="wrap">  
                <button class="clicker fast" style="font-size: 1rem">Add</button>
                <div class="circle angled second"></div>
            </div>
        </form>
    </div>

    <h2 class='OpenSansFont center' style="padding-top: 10px;">List Friend</h2>
    <div class='box-table'>
        {% for i in friend %}
        <div class='box-view'>
                {{i.name}}
                <a class='right-text' href="{{i.url}}">{{i.url}} </a>
                <br>
                <div class="right-text" style='font-size: 0.875rem'><i>added </i>{{i.created_date}}</div>
                       
        </div>
        <br>
        {% endfor %}

    </div>


</body>
</html>

add_friend/templates/partials/footer.html
<p>&copy; Made by Team PePeW</p>

add_friend/templates/partials/header.html
<div class="topnav" id="myTopnav">
  <a href="">Stats</a>
  <a href="">Friends</a>
  <a href="">Profile</a>
  <a href="">Status</a>
  <a href="javascript:void(0);" class="icon" onclick="myFunction()">&#9776;</a>
</div>

dashboard/templates/dashboard/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Dashboard">
    <meta name="author" content="{{author}}">
	<meta name="friend" content="{{friend}}">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'header.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface" rel="stylesheet">
    <!-- bootstrap csss -->

    <title>
        {% block title %} Status page By {{author}} {% endblock %}
    </title>
</head>

<body>
    <header>
        {% include "dashboard/partials/header.html" %}
    </header>
    <content>
		<h2> Statistic </h2>
		 <h3 class="tab">
			<img  style="margin-left: 250px;border-radius:50%;"  src="http://pre00.deviantart.net/3d69/th/pre/i/2013/214/9/3/lion_of_judah_by_janmil000-d6gahv0.jpg" height="200" width="200"  style="vertical-align:middle">
			PePeW
		</h3>
		<br/>
		<br/>
		
		<h4 style="text-align:left;margin-left: 300px;">
		 <img style = "margin-left:10px;" src = "https://cdn3.iconfinder.com/data/icons/blog-and-social-media-icons/512/Add_Friend-512.png" height="50" width = "50">
		 Friends: {{friend}} 
		<img style = "margin-left:300px;" src = "http://cdn.mysitemyway.com/etc-mysitemyway/icons/legacy-previews/icons/matte-white-square-icons-social-media-logos/125777-matte-white-square-icon-social-media-logos-mail-square.png" height="50" width = "50")
		<span style="float:right;margin-right: 300px;"> 
		Feed: </span>
		</h4>
		<br/>
		
		<h4 style="margin-left:300px;"> Latest Post </h4>
		<h4 class="tab">
			<img  style="margin-left: 250px;"  src="http://pre00.deviantart.net/3d69/th/pre/i/2013/214/9/3/lion_of_judah_by_janmil000-d6gahv0.jpg" height="100" width="100"  style="vertical-align:middle">
			PePew
		</h4>
		
	</content>
    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include "dashboard/partials/footer.html" %}
        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script type="text/javascript" src="header.js"></script>

</body>
</html>

dashboard/templates/dashboard/partials/footer.html
<p>&copy; Made by Team PePeW</p>

dashboard/templates/dashboard/partials/header.html
<div class="navbar navbar-default navbar-static-top"role="navigation">
   <div class="container">
     <div class="navbar-header">
       <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
         <span class="sr-only">Toggle navigation</span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
       </button>
       <div class="small-logo-container">
         <a class="small-logo" href="/dashboard/" color=light-blue>LingIn</a>
	   </div>
     </div>
     <div class="navbar-collapse collapse">
	   <ul class="nav navbar-nav navbar-right">
         <li><a href="/update-status/">Status</a></li>
         <li><a href="/page_profile/">Profile</a></li>
         <li><a href="/add-friend/">Friends</a></li>
         <li class="active"><a href="/dashboard/">Stats</a></li>
       </ul>
     </div><!--/.nav-collapse -->
   </div>
 </div>

dashboard/templates/footer.html
<!-- TODO, CREATE THIS FILE AND ADD copyright symbol -->
<p>&copy; Made by Team PePeW</p>

dashboard/templates/header.html
<style>
.navbar-nav{
  width: 90%;
}
ul{
  list-style-type:none;
  display:flex;
  justify-content: center;

}
ul li{
  display: list-item;
  background: transparent;
  padding: 1px 10px;
  color:white;
  margin: 0 3px;
  font-family: "Proxima Nova";
}

</style>

<nav class = "navbar navbar-center navbar-inverse navbar-static-top">
  <div class = "container-fluid">
    <div class = "navbar-header">
      <button type = "button" class = "navbar-toggle collapsed" data-toggle = "collapse" data-target="#navbar" aria-expanded = "false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand logo-utama-lingin">lingin</a>
    </div>
    <div class="collapse navbar-collapse"id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'update-status:index' %}">Status</a></li>
        <li><a>Profile</a></li>
        <li><a href="{% url 'add-friend:index' %}">Friends</a></li>
        <li><a href="{% url 'dashboard:index' %}">Stats</a></li>
      </ul>
    </div>
  </div>
</nav>

dashboard/templates/statistic.html
{% extends "update_status/layout/cobaBase.html" %}
{% block content %}

<h1>Statistic</h1>
<img src="https://go2olymp.com/files/587501921759e/5875ce5256eab.jpg" style="margin-top:30px;margin-left:400px; width:200px; height:200px; border-radius:50%;"></p1>
<br>
<p1 style="font-size:150%; margin-left:400px">{{author}}</p1>
<pre style="margin-left:400px; font-size:120%;">
Friends		:{{friend}}
Feed		:{{posts}}
Latest Post	:{{latest_post}}
                 {{date}}
</pre>
{% endblock %}

page_profile/templates/page_profile/tampilan.html
<!-- {% extends "update_status/layout/cobaBase.html" %} -->
{% load staticfiles %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
	<link rel='stylesheet' type='text/css' href={% static 'CSS/profile_page.css' %}/>
    <title>My Profile</title>
	
</head>
<!--style>
    table, th, td {
        border: 1px solid black;
    }
    .subject{
        font-size: 20px;
        font-family: "Comic Sans MS";
        color: #6650ff;
    }
    .value{
        font-size: 20px;
        font-family: "Roboto", "Lucida Grande", Verdana, Arial, sans-serif;
        color: #ff102c;
    }
</style-->
<body style = 'background-color: #ACFA58'>

	<div> 
		<img class='photoProfile' src="{% static '/image/coba.jpg' %}" alt= "My Image">
	</div>
	<div class= 'style_name' style="text-align: center">{{name}}</div>
	<div class= 'style_fontTable'>
	<div>
	<table class = 'biodata' align="center" style="text-align: left">
	<tr> 
		<td class = 'size_column'>Birthday</td>
		<td class = 'size_column_2'>{{ bday }}</td>
	</tr>
	<tr>	
		<td>Gender</td>
		<td>{{gender}}</td>
	</tr>
	<tr>	
		<td>Expertise</td>
		<td> {% for i in expertise %}
				<li class = 'style_font' style="text-align: left">{{i}} </li>
			{% endfor %} </td>
	</tr>
	<tr>	
		<td>Description</td>
		<td>{{desc}}</td>
	</tr>
	<tr>	
		<td>Email</td>
		<td>{{email}}</td>
	</tr>
	</table>
	</div>
</body>
</html>
	{% endblock %}

update_status/templates/update_status/addComment.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'css/update_status.css' %}" />
    <title>
        Comment
    </title>
</head>
<body class="body">
  <div class="centered">
  	<div class="form-panel-head">
  		<form id="form" method="POST" action="{% url 'update-status:save-comment' pk=posted.id %}">
  			{% csrf_token %}
  			{{ post_forms }}
  			<br>
  			<button class="button-design" type="submit">Submit</button>
  			<a class="cancel-design" href="{% url 'update-status:cancel' %}">Cancel</a>
  		</form>
  	</div>
  </div>
</body>
</html>

update_status/templates/update_status/layout/cobaBase.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'css/update_status.css' %}" />
	<link rel='stylesheet' type='text/css' href="{% static 'CSS/page_profile.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/add_friend.css' %}" /> 
</head>
<body class="body">
	<header>
        {% include "dashboard/partials/header.html" %}
	</header>
	<content>
		<div>
				{% block content %}
				{% endblock %}
		</div>
	</content>
	<footer>
        {% include "dashboard/partials/footer.html" %}
    </footer>
</body>
</html>

update_status/templates/update_status/updateStatus.html
{% extends "update_status/layout/cobaBase.html" %}
{% load staticfiles %}
	{% block content %}
		<div class="form-panel-head">
			<h1 class="data">Update Status</h1>
			<form id="form" method="POST" action="{% url 'update-status:add-post' %}">
					{% csrf_token %}
					{{ post_form }}
					<br>
				<button class="button-design" type="submit">Post</button>
			</form>
		</div>
		<div class="container">
			<div class="flex">
			  {% for i in post %}
				<div class="flex-item">
					<div class="posts">
						<p><img class="photoProfile2" src="{% static '/image/coba.jpg' %}">{{nama}}</p>
						<div>
							<p style="white-space:pre">{{i.post}}</p>
						</div>
						<div class="post-date">{{i.created_date|date:"d M Y G:i:s"}}</div>
						<div class="button-wraper">
						<a class="comment-design" href="{% url 'update-status:add-comment' pk=i.id %}">Comment</a>
						</div>
						{% for x in comments %}
							{% if x.post.id == i.id %}
								<div class="flex-item">
									<div class="posts">
										<!--div class="post-profile">
										</div-->
										<div>
											<p style="white-space:pre">{{x.comment}}</p>
										</div>
										<div class="post-date">{{x.created_date|date:"d M Y G:i:s"}}</div>
									</div>
								</div>
							{% endif %}
						{% endfor %}
					</div>
				</div>
			  {% endfor %}
			</div>
		</div>
	{% endblock %}